### ISSUE TITLE
README.md required.

### ISSUE THREAD

**Issue by brookmg** [Khalid-Sultan/paxos#1]
- It would be better if you have Readme file to show some kind of description of the program you wrote 👍🏽

**Comment by Khalid-Sultan** [comment]
Sorry this was just a first try at Paxos since I'm studying it. I have exams these two weeks. But I definitely will keep it updated when I progress this one into an actual project after the exams.

**Comment by brookmg** [comment]
Sure. It just seemed a lot of stuff for a single commit.
